### ISSUE TITLE
Add execution time of submissions on the leaderboard

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#3315]
**Issue:**
We want to display the execution time of the submissions for a specific phase split leaderboard.

**Tasks:**
- [ ] Add a boolean field `show_execution_time` with `default=False` in the ChallengePhaseSplit model.
- [ ] Add the field in the `ChallengePhaseSplitSerializer`.
- [ ] While filtering the query set in the `calculate_distinct_sorted_leaderboard_data` function, use the above field to annotate the query set with the `execution_time` field.
- [ ] On the UI in the `leaderboard.html`, add a new column with name `Execution time (sec.)` for the execution time before `Submitted at` and use `challenge.selectedPhaseSplit.show_execution_time` to show and hide that column with the values.

Please feel free to ask if you have any doubts/questions.

**Note:** This is a high _very priority issue_, please pick it up only when a PR can be opened within 24 hours.

**Comment by RishabhJain2018** [comment]
@burnerlee Would you like to work on this?

**Comment by burnerlee** [comment]
@RishabhJain2018 yeah sure

**Comment by burnerlee** [comment]
I'll start right away

**Comment by burnerlee** [comment]
@RishabhJain2018 @Ram81 could you please tell me how to run makemigrations using docker-compose?

**Comment by burnerlee** [comment]
figured it out

**Comment by burnerlee** [comment]
@RishabhJain2018 @Ram81 made a PR for the above changes. Do we also need to allow user to sort the leaderboard table according to the execution time. Currently not implemented this sorting feature, as was not mentioned in the issue

**Comment by RishabhJain2018** [comment]
>Do we also need to allow user to sort the leaderboard table according to the execution time? Currently not implemented this sorting feature, as was not mentioned in the issue

@burnerlee Yes, please add that as well.

**Comment by Alabhya268** [comment]
> figured it out

@burnerlee could you also tell me how to do it in Linux?

**Comment by burnerlee** [comment]
Hey @Alabhya268 sure, actually i executed the command by entering into the docker container using exec... Start evalai using docker-compose up. In another terminal, run `docker ps` to see all containers. Copy the id of the django docker container. then use the command `docker exec -i -t <container-id>` and would be inside the container. Then simply run `python manage.py makemigrations`. Migrations are applied automatically when we run evalai, so restart it once.

**Comment by burnerlee** [comment]
https://stackoverflow.com/questions/33992867/how-do-you-perform-django-database-migrations-when-using-docker-compose see this for reference
