### ISSUE TITLE
Add support to reload worker whenever Challenge or Challenge Phase file changes

### ISSUE THREAD

**Issue by taranjeet** [Cloud-CV/EvalAI#842]
Description: The worker when starts loads all the active challenges and challenge phase. It fetches `evaluation_script` for Challenge and `test_annotation` for Challenge Phase and stores them on disk.

Now if the Challenge Host updates any of these files, then should be reflected in the worker also.

We need to add support for this

It is a big issue, Hence it will involve many sub-issues

- [ ] Log change in Challenge and Challenge Phase model when file fields are updated, Issue [839](https://github.com/Cloud-CV/EvalAI/issues/839)
- [ ] Add support in submission worker to update file field changes for Challenge and Challenge Phase, Issue [840](https://github.com/Cloud-CV/EvalAI/issues/840)
- [ ] Publish message whenever file field of Challenge and Challenge Phase changes, Issue [841](https://github.com/Cloud-CV/EvalAI/issues/841)

Note: This issue on its own does not require any coding, Just that it will help us to track the progress  of individual sub-issues and have a broader picture here.

**Comment by isht3** [comment]
@taranjeet Can I take this up?

**Comment by taranjeet** [comment]
@deshraj @RishabhJain2018 : Same for this issue. If not required can we please close it?

**Comment by deshraj** [comment]
We would need this feature really soon after migrating to SQS #1752. Closing as of now since the issue description is outdated now.
